spring.application.name=backend

api.security.token.secret=${JWT_SECRET:reidocabecote}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:reidocabecote}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:123Teste}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8081}
server.address=0.0.0.0
